name: Deploy React Gatsby Blog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user information
      - run: git config --global user.email "gwiyeomgo@gmail.com"
      - run: git config --global user.name "gwiyeomgo"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Yarn Develop
        run: yarn develop