name: Deploy React Gatsby Blog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
          token: ${{secrets.PAT}}
          username: ${{secrets.USERNAME}}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Yarn Develop
        run: yarn develop